USE [Welland_Sandbox]
GO

/****** Object:  StoredProcedure [dbo].[uspPROP_MAP]    Script Date: 1/4/2021 1:50:18 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


-- ============================================================================
-- Author: Heath Cameron
-- Create date: 12/5/2019
--
--
-- Sample invocation:
-- Exec [dbo].[uspPROP_MAP] 0, 0, 0, 0 
--
-- Change log:
--   logic.
-- ============================================================================

	---------------------------------------------------------------------------
	-- Empty Table.
	---------------------------------------------------------------------------

	TRUNCATE TABLE MAP.PROP_XREF

	---------------------------------------------------------------------------
	-- Insert records.
	---------------------------------------------------------------------------

 --FORMAT SUPPLEMENTAL WELL LIST

IF EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'WELL_EXCEL'
                      AND COLUMN_NAME = 'COST_CENTER'
                      AND TABLE_SCHEMA='SUP')
  BEGIN
      ALTER TABLE SUP.WELL_EXCEL
        DROP COLUMN COST_CENTER
  END

	ALTER TABLE SUP.WELL_EXCEL
    ADD COST_CENTER VARCHAR(10);

UPDATE SUP.WELL_EXCEL
SET COST_CENTER = CONVERT (VARCHAR(50), [Cost Center],0)

---INSERT ALL WELLS

	INSERT INTO MAP.PROP_XREF
		(
		[PAR_PROP_NO] ,
		[JAG_PROP_NO],
		[EXISTED_IN_Q],
	    [MDM_PROP],
		[PROP_NM],
		[PROP_TYPE]
	)
	SELECT 
	CASE WHEN [OPERATOR] <> '600' THEN CONCAT('3',COST_CENTER_REF,'J') ELSE CONCAT(COST_CENTER_REF,'J') END,
	COST_CENTER_REF,
	'N',
	NULL,--CASE WHEN [OPERATOR] = '600' AND [Property Type] = 'WL' THEN 'Y' ELSE 'N' END,
	[DESCRIPTION],
	COALESCE([Property Type],'GA')
	FROM Welland_Export_Prod.dbo.WELL_MASTER
	LEFT JOIN SUP.WELL_EXCEL
	ON [COST_CENTER] = COST_CENTER_REF


-- INSERT COST CENTERS THAT ARE NOT WELLS BUT HAVE BEEN USED FOR GL ENTRIES 

	INSERT INTO MAP.PROP_XREF
		(
		[PAR_PROP_NO] ,
		[JAG_PROP_NO],
		[EXISTED_IN_Q],
	    [MDM_PROP],
		[PROP_NM],
		[PROP_TYPE]
	)
	SELECT DISTINCT
     CASE WHEN [OPERATOR] <> '600' THEN CONCAT('3',C.COST_CENTER_REF,'J') 
	 WHEN C.COST_CENTER_REF LIKE '%TX%' THEN CONCAT(REPLACE(C.COST_CENTER_REF,'.0','.'),'J')
	 ELSE CONCAT(C.COST_CENTER_REF,'J') END,
	 C.COST_CENTER_REF,
	--C.COST_CENTER_REF, [NAME],
	'N',
	'N',
	UPPER([NAME]),
	'GA'
	 FROM Welland_Export_Prod.dbo.CCM C
	LEFT JOIN (select DISTINCT COST_CENTER_REF_RR750 FROM Welland_Export_Prod.dbo.UTM_ASSOC1) GL
	ON COST_CENTER_REF_RR750 = COST_CENTER_REF
	LEFT JOIN (SELECT DISTINCT REPLACE(U2_ID, '600*','') AS WELL FROM Welland_Export_Prod.dbo.WELL_MASTER_ASSOC8) H
	ON H.WELL = COST_CENTER_REF
	LEFT JOIN Welland_Export_Prod.dbo.WELL_MASTER W
	ON W.COST_CENTER_REF = C.COST_CENTER_REF
	LEFT JOIN MAP.PROP_XREF
	ON JAG_PROP_NO = C.COST_CENTER_REF
	WHERE (COST_CENTER_REF_RR750 IS NOT NULL 
	OR WELL IS NOT NULL)
	AND W.COST_CENTER_REF IS NULL 
	AND JAG_PROP_NO IS NULL

--INSERT BATTERIES 

INSERT INTO MAP.PROP_XREF
		(
		[PAR_PROP_NO] ,
		[JAG_PROP_NO],
		[EXISTED_IN_Q],
	    [MDM_PROP],
		[PROP_NM],
		[PROP_TYPE]
	)
SELECT DISTINCT 
CONCAT(600500 + dense_rank()  OVER ( order by [Facility Name]),'J')
, NULL
, 'N'
, 'N'
, UPPER([Facility Name])
,'AL'
FROM SUP.BATTERY_LIST
WHERE [Well Name] IS NOT NULL
OR [Well Name] <> 0 

--WELLS THAT WERE NOT IN EXCALIBUR BUT WERE LOADED THROUGH MDM

INSERT INTO MAP.PROP_XREF
		(
		[PAR_PROP_NO] ,
		[JAG_PROP_NO],
		[EXISTED_IN_Q],
	    [MDM_PROP],
		[PROP_NM],
		[PROP_TYPE]
	)
SELECT DISTINCT 
PROP_NO, 
NULL, 
'Y',
'Y',
PROP_NM,
PROP_TYPE_CD
 FROM QAS.GONL_PROP
WHERE PROP_NO IN ('10476J',
'10477J','10478J','10479J',
'10480J','10481J','10482J',
'10483J','10484J','10485J',
'10486J','10487J','10488J',
'10489J','10490J','10492J')

--UPDATES BASED ON COURTNEY ROACH'S EMAIL 

UPDATE A
SET PAR_PROP_NO = B.PAR_PROP_NO
FROM MAP.PROP_XREF A
INNER JOIN (
SELECT 'ACCT' AS JAG_PROP_NO, '222006J' AS PAR_PROP_NO
UNION SELECT '600A' AS JAG_PROP_NO, '222006J' AS PAR_PROP_NO
UNION SELECT 'FIELD' AS JAG_PROP_NO, '222036J' AS PAR_PROP_NO
UNION SELECT 'FIN' AS JAG_PROP_NO, '222006J' AS PAR_PROP_NO
UNION SELECT '02.9999' AS JAG_PROP_NO, '222228J' AS PAR_PROP_NO
UNION SELECT 'FTSTCN' AS JAG_PROP_NO, '222228J' AS PAR_PROP_NO
UNION SELECT 'GEO' AS JAG_PROP_NO, '222003J' AS PAR_PROP_NO
UNION SELECT 'HR' AS JAG_PROP_NO, '222008J' AS PAR_PROP_NO
UNION SELECT 'IR' AS JAG_PROP_NO, '222007J' AS PAR_PROP_NO
UNION SELECT 'IT' AS JAG_PROP_NO, '222009J' AS PAR_PROP_NO
UNION SELECT 'LAND' AS JAG_PROP_NO, '222004J' AS PAR_PROP_NO
UNION SELECT 'LEGAL' AS JAG_PROP_NO, '222005J' AS PAR_PROP_NO
UNION SELECT 'OPS' AS JAG_PROP_NO, '222001J' AS PAR_PROP_NO
UNION SELECT 'RES' AS JAG_PROP_NO, '222017J' AS PAR_PROP_NO
UNION SELECT '01.9999' AS JAG_PROP_NO, '222234J' AS PAR_PROP_NO
) B
ON B.JAG_PROP_NO = A.JAG_PROP_NO

--DUPLICATE PROPERTIES
UPDATE MAP.PROP_XREF
SET IMPORT = 'N'
WHERE JAG_PROP_NO IN ('600A','FIN', '02.9999')

--WATER ASSETS 

INSERT INTO MAP.PROP_XREF
		(
		[PAR_PROP_NO] ,
		[JAG_PROP_NO],
		[EXISTED_IN_Q],
	    [MDM_PROP],
		[PROP_NM],
		[PROP_TYPE]
	)
SELECT DISTINCT 
[Property Number]
, NULL
, 'N'
, 'N'
, UPPER([Property Name])
,[Type]
FROM SUP.WATER_ASSETS

--IF WELL IS NOT ON ANY ENTRIES THERE IS NO NEED TO LOAD. 

UPDATE A
SET IMPORT = 'N' 
FROM MAP.PROP_XREF A
INNER JOIN 
(select PAR_PROP_NO from MAP.PROP_XREF
LEFT JOIN Welland_Export_Prod.dbo.UTM_ASSOC1
ON REPLACE(COST_CENTER_REF_RR750,'600*','') = JAG_PROP_NO
WHERE EXISTED_IN_Q <> 'Y'
AND JAG_PROP_NO IS NOT NULL
GROUP BY PAR_PROP_NO 
HAVING COUNT(u2_id) = 0 
OR COUNT(u2_id) IS NULL ) B
ON A.PAR_PROP_NO = B.PAR_PROP_NO

UPDATE A
SET IMPORT = 'Y' 
FROM MAP.PROP_XREF A
INNER JOIN Welland_Export_Prod.dbo.WELL_MASTER_ASSOC8 W
ON REPLACE(u2_id,'600*','') = JAG_PROP_NO
LEFT JOIN  Welland_Export_Prod.DBO.AFE_MASTER M
ON W.U2_ID = LEFT(M.U2_ID, 9)
WHERE EXISTED_IN_Q <> 'Y'
AND JAG_PROP_NO IS NOT NULL
AND M.TYPE_CODE IN ('DC','DAFE','FAC','REC')

 -- CHECK TO MAKE SURE PROPERTY DOESN'T ALREADY EXIST IN QUORUM. NEED TO LOAD GONL PROP AFTER EACH ROUND

UPDATE A
SET EXISTED_IN_Q = 'Y'
, IMPORT = 'Y' 
FROM MAP.PROP_XREF A
INNER JOIN QAS.GONL_PROP
ON PAR_PROP_NO = PROP_NO

UPDATE MAP.PROP_XREF
SET EXISTED_IN_Q = 'N'
WHERE EXISTED_IN_Q <> 'Y'
or EXISTED_IN_Q is null 

UPDATE MAP.PROP_XREF
SET IMPORT = 'Y'
WHERE IMPORT IS NULL

--UPDATE MDM FLAG TO NOT BE NULL 

UPDATE MAP.PROP_XREF
SET MDM_PROP = 'N'
WHERE MDM_PROP IS NULL

--UPDATE TYPES -- ONE OFFS

UPDATE A
SET PROP_TYPE = B.PROP_TYPE
FROM MAP.PROP_XREF A
INNER JOIN (SELECT '20004J' AS PAR_PROP_NO, 'FP' AS PROP_TYPE--DO NOT USE-SECTION 96 FRAC PIT
--'20005J', --DO NOT USE-COCHISE SWD
UNION SELECT '20006J', 'FP'--DO NOT USE-SEC 14 FRAC PIT
--'20007J' --DO NOT USE - SEC 14 SWD
--'10388J' --DO NOT USE VENOM 6162A-34-21H
--'20000J' --DO NOT USE-COCHISE WATER WELL
--'20001J' --DO NOT USE-WHISKEY RIVER SWD
UNION SELECT '20002J', 'FP'--DO NOT USE-COCHISE FRAC POND
UNION SELECT '50000J', 'GA'
) B 
ON A.PAR_PROP_NO = B.PAR_PROP_NO

--UPDATE DO NOT USE NAMES

UPDATE A
SET PROP_NM = B.PROP_NM
--select * 
FROM MAP.PROP_XREF A
 INNER JOIN (SELECT 'DO NOT USE CL 2122A-C2-1H' AS PROP_NM_OLD,'DO NOT USE - CL 2122A-C2-1H' AS PROP_NM
UNION SELECT '*DO NOT USE* UTL 2714A-17 1H','DO NOT USE - UTL 2714A-17 1H'
UNION SELECT '*DNU* BIG TEX SO 2524A-143 1H','DO NOT USE - BIG TEX SO 2524A-143 1H'
UNION SELECT 'DNU BIG TEX SOUTH 1516A-143 1H','DO NOT USE - BIG TEX SOUTH 1516A-143 1H'
UNION SELECT 'DO NOT USE WR 19.5B-8-1H','DO NOT USE - WR 19.5B-8-1H'
UNION SELECT '*DNU* CARNAGE 6261B-34 1H','DO NOT USE - CARNAGE 6261B-34 1H'
UNION SELECT '*DNU* CARNARGE 6261C-34 1H','DO NOT USE - CARNARGE 6261C-34 1H' AS PROP_NM
UNION SELECT 'UTL L J BELDIN 1211-17 41H-DNU','DO NOT USE - UTL L J BELDIN 1211-17 41H' AS PROP_NM
UNION SELECT 'DNU ST NEAL LETHC 1213-143 81H' AS PROP_NM_OLD,'DO NOT USE - ST NEAL LETHC 1213-143 81H' AS PROP_NM
UNION SELECT 'DO NOT USE' AS PROP_NM_OLD,'DO NOT USE - CANCELLED JAG WELL' AS PROP_NM
UNION SELECT 'DO NOT USE VENOM 6162A-34-11H' AS PROP_NM_OLD,'DO NOT USE - VENOM 6162A-34-11H' AS PROP_NM
UNION SELECT 'DO NOT USE VENOM 6162A-34-21H' AS PROP_NM_OLD,'DO NOT USE - VENOM 6162A-34-21H' AS PROP_NM
UNION SELECT 'DO NOT USE-COCHISE WATER WELL' AS PROP_NM_OLD,'DO NOT USE - COCHISE WATER WELL' AS PROP_NM
UNION SELECT 'DO NOT USE-WHISKEY RIVER SWD' AS PROP_NM_OLD,'DO NOT USE - WHISKEY RIVER SWD' AS PROP_NM
UNION SELECT 'DO NOT USE-COCHISE FRAC POND' AS PROP_NM_OLD,'DO NOT USE - COCHISE FRAC POND' AS PROP_NM
UNION SELECT 'DO NOT USE-SECTION 96 FRAC PIT' AS PROP_NM_OLD,'DO NOT USE - SECTION 96 FRAC PIT' AS PROP_NM
UNION SELECT 'DO NOT USE-COCHISE SWD' AS PROP_NM_OLD,'DO NOT USE - COCHISE SWD' AS PROP_NM
UNION SELECT 'DO NOT USE-SEC 14 FRAC PIT' AS PROP_NM_OLD,'DO NOT USE - SEC 14 FRAC PIT' AS PROP_NM
UNION SELECT 'DO NOT USE - SEC 14 SWD' AS PROP_NM_OLD,'DO NOT USE - SEC 14 SWD' AS PROP_NM
UNION SELECT '*DNU* ROOSTERFISH 22NE81 #81' AS PROP_NM_OLD,'DO NOT USE - ROOSTERFISH 22NE81 #81' AS PROP_NM
UNION SELECT '*DNU* ROOSTERFISH 22SE83 #83' AS PROP_NM_OLD,'DO NOT USE - ROOSTERFISH 22NE81 #81' AS PROP_NM
UNION SELECT '*DNU* ROOSTERFISH 22SE #63H' AS PROP_NM_OLD,'DO NOT USE - ROOSTERFISH 22NE81 #81' AS PROP_NM
) B
ON A.PROP_NM = B.PROP_NM_OLD

--MARK MDM PROPERTIES 

UPDATE A
SET MDM_PROP = CASE WHEN B.PROP_NO IS NULL THEN 'N' ELSE 'Y' END 
FROM MAP.PROP_XREF A
LEFT JOIN QAS.GONL_PROP_ATTR B
ON A.PAR_PROP_NO = B.PROP_NO 
AND ATTR_TYPE_CD = 'WI'

--ELIMINATE DO NOT USE PROPERTY THAT LINK TO ACTIVE PROPERTIES

UPDATE A
SET PAR_PROP_NO = B.PAR_PROP_NO
, IMPORT = 'N'
FROM MAP.PROP_XREF A
INNER JOIN
(SELECT '10123' JAG_PROP_NO, '340026J' PAR_PROP_NO 
 UNION SELECT '10124' JAG_PROP_NO, '340032J' PAR_PROP_NO
 union select '10126' JAG_PROP_NO, '340033J' PAR_PROP_NO
 union select '10129' JAG_PROP_NO, '340028J' PAR_PROP_NO
 union select '10125' JAG_PROP_NO, '340027J' PAR_PROP_NO) B
 ON A.JAG_PROP_NO = B.JAG_PROP_NO

 --PLANNED WELLS THAT WERE UPLOADED THROUGH EPEX

 UPDATE A
SET IMPORT = 'N'
FROM MAP.PROP_XREF A
WHERE JAG_PROP_NO IN ('10413',
'10414',
'10415',
'10429',
'10430',
'10431'
)

--ADDRESSING DUPLICATE WELLS 

UPDATE A 
SET PAR_PROP_NO = PAR
, IMPORT = 'N'
FROM MAP.PROP_XREF A
INNER JOIN 
(SELECT '10403' AS JAG, '10488J' AS PAR
UNION SELECT '10404' AS JAG, '10489J' AS PAR
UNION SELECT '10405' AS JAG, '10490J' AS PAR
UNION SELECT '10406' AS JAG, '10492J' AS PAR) B 
ON B.JAG= JAG_PROP_NO 

--ADDRESSING NON-OP WELL 

UPDATE A 
SET PAR_PROP_NO = PAR
, IMPORT = 'Y'
, PROP_TYPE = 'WL'
FROM MAP.PROP_XREF A
INNER JOIN 
(SELECT '40074' AS JAG, '340074J' AS PAR) B
ON B.JAG= JAG_PROP_NO 

--WELL WITH EPEX NUMBERS

UPDATE A 
SET PAR_PROP_NO = PAR
FROM MAP.PROP_XREF A
INNER JOIN 
(SELECT '10413' AS JAG, '501665' AS PAR
UNION SELECT '10414' AS JAG, '501666' AS PAR
UNION SELECT '10415' AS JAG, '501667' AS PAR
UNION SELECT '10429' AS JAG, '501668' AS PAR
UNION SELECT '10430' AS JAG, '501669' AS PAR
UNION SELECT '10431' AS JAG, '501670' AS PAR
) B
ON B.JAG= JAG_PROP_NO 

-- FLAG FLIP ON "IN QUORUM"

UPDATE A
SET EXISTED_IN_Q = 'Y'
FROM MAP.PROP_XREF A
INNER JOIN QAS.GONL_PROP
ON PAR_PROP_NO = PROP_NO

END 
























GO


