/*Properties with the following gas purchasers will be changed. 
TARGA - 9376
WTG	- 3003
ETC	- 10065
ENLINK - 25855 -already remit
BRAZOS - 13479 -already remit
*/

PRINT ' '
PRINT 'DISABLE PPN TRIGGERS'

ALTER TABLE RONL_DO_ACCTG_DATA DISABLE TRIGGER [TR_PPN_RONL_DO_ACCTG_DATA_IUD]
ALTER TABLE RONL_DO_ACCTG_DATA_TAX DISABLE TRIGGER [TR_PPN_RONL_DO_ACCTG_DATA_TAX_IUD]

PRINT ' '
PRINT 'CREATE PROPERY  LIST'

SELECT DISTINCT PROP_NO INTO #PROP_LIST FROM RTRN_BCH_SEL_HIST
WHERE PRDN_DT = '6/1/2019'
AND MAJ_PROD_CD IN ('200','400')
AND RMITR_NO IN ('9376','3003','10065')

--DROP TABLE #PROP_LIST
PRINT ' '
PRINT 'PUT CURRENT RULES INTO TEMP TABLES'

SELECT * INTO #ACCT_RULES
FROM RONL_DO_ACCTG_DATA 
WHERE EFF_DT_TO = '12/31/9999'
AND MAJ_PROD_CD IN ('400', '200')
AND DO_TYPE_CD = 'REV'
AND PROP_NO IN (SELECT PROP_NO FROM #PROP_LIST)

SELECT * INTO #TAX
FROM RONL_DO_ACCTG_DATA_TAX
WHERE EFF_DT_TO = '12/31/9999'
AND MAJ_PROD_CD IN ('400', '200')
AND DO_TYPE_CD = 'REV'
AND PROP_NO IN (SELECT PROP_NO FROM #PROP_LIST)
AND SEV_TAX_TYPE_CD in ('PR','FE')

PRINT ' '
PRINT 'END DATE CURRENT ACCOUNTING RULES'

UPDATE RONL_DO_ACCTG_DATA_TAX
SET EFF_DT_TO = '6/30/2019',
UPDT_USER = 'SCRIPT',
UPDT_DT = CONVERT(SMALLDATETIME, Getdate())
WHERE EFF_DT_TO = '12/31/9999'
AND MAJ_PROD_CD IN ('400', '200')
AND DO_TYPE_CD = 'REV'
AND PROP_NO IN (SELECT PROP_NO FROM #PROP_LIST)

UPDATE RONL_DO_ACCTG_DATA
SET EFF_DT_TO = '6/30/2019',
UPDT_USER = 'SCRIPT',
UPDT_DT = CONVERT(SMALLDATETIME, Getdate())
WHERE EFF_DT_TO = '12/31/9999'
AND MAJ_PROD_CD IN ('400', '200')
AND DO_TYPE_CD = 'REV'
AND PROP_NO IN (SELECT PROP_NO FROM #PROP_LIST)

PRINT ' '
PRINT 'INSERT NEW RULES'

INSERT INTO [dbo].[RONL_DO_ACCTG_DATA]
           ([PROP_NO]
           ,[DO_TYPE_CD]
           ,[DO_MAJ_PROD_CD]
           ,[TIER]
           ,[OPER_BUS_SEG_CD]
           ,[MAJ_PROD_CD]
           ,[EFF_DT_FROM]
           ,[EFF_DT_TO]
           ,[PMT_LVL_MP_NO]
           ,[VL_PROC_TYPE_CD]
           ,[BK_LAG_TIME]
           ,[ACT_DO_CD]
           ,[CURR_HIST_DO_CD]
           ,[LSE_USE_FL]
           ,[UPDT_USER]
           ,[UPDT_DT]
           ,[WELL_NO]
           ,[COMPL_NO])
SELECT DISTINCT
           PROP_NO
           ,DO_TYPE_CD
           ,DO_MAJ_PROD_CD
           ,TIER
           ,OPER_BUS_SEG_CD
           ,MAJ_PROD_CD
           ,'7/1/2019'
           ,'12/31/9999'
           ,PMT_LVL_MP_NO
           ,VL_PROC_TYPE_CD
           ,BK_LAG_TIME
           ,ACT_DO_CD
           ,CURR_HIST_DO_CD
           ,LSE_USE_FL
           ,'SCRIPT'
           ,CONVERT(SMALLDATETIME, Getdate())
           ,WELL_NO
           ,COMPL_NO
FROM #ACCT_RULES

INSERT INTO [dbo].[RONL_DO_ACCTG_DATA_TAX]
           ([PROP_NO]
           ,[DO_TYPE_CD]
           ,[DO_MAJ_PROD_CD]
           ,[TIER]
           ,[OPER_BUS_SEG_CD]
           ,[MAJ_PROD_CD]
           ,[SEV_TAX_TYPE_CD]
           ,[EFF_DT_FROM]
           ,[EFF_DT_TO]
           ,[TAX_PAY_CD]
           ,[TAX_RPT_CD]
           ,[UPDT_USER]
           ,[UPDT_DT])
SELECT DISTINCT
           PROP_NO
           ,DO_TYPE_CD
           ,DO_MAJ_PROD_CD
           ,TIER
           ,OPER_BUS_SEG_CD
           ,MAJ_PROD_CD
           ,SEV_TAX_TYPE_CD
           ,'7/1/2019'
           ,'12/31/9999'
           ,'Y'
           ,1
           ,'SCRIPT'
           ,CONVERT(SMALLDATETIME, Getdate())
FROM #TAX

PRINT ' '
PRINT 'DROP TEMP TABLES'

DROP TABLE #ACCT_RULES
DROP TABLE #TAX
DROP TABLE #PROP_LIST

PRINT ' '
PRINT 'ENABLE TRIGGERS'

ALTER TABLE RONL_DO_ACCTG_DATA ENABLE TRIGGER [TR_PPN_RONL_DO_ACCTG_DATA_IUD]
ALTER TABLE RONL_DO_ACCTG_DATA_TAX ENABLE TRIGGER [TR_PPN_RONL_DO_ACCTG_DATA_TAX_IUD]



